### ISSUE TITLE
afterAll (tearDown) support?

### ISSUE THREAD

**Issue by nkzawa** [zeit/best#11]
With `best`, I think it's expected to clean up everything per a test, but sometimes, you want to tear down only after all tests finish in case making tests faster.

For example, can we support exporting special name functions like:
```js
// this is not counted as a test and ensured to be called after all tests in this file.
exports.afterAll = () => {
  // do clean up
}
```

**Comment by Qix-** [comment]
This is what exit hooks are for - I'm against any magic naming convention; it was something I wanted to get away from with `best`.

**Comment by nkzawa** [comment]
Do you mean the `exit` event of `process`? I wonder how do you use it when you want to start a server only once, for example.

**Comment by Qix-** [comment]
> I wonder how do you use it when you want to start a server only once

I'm not sure what you mean here - just initialize things in the file-local scope

**Comment by nkzawa** [comment]
I meant if you run a server like that, there is no timing to gracefully stop it and the process never finish.

**Comment by TooTallNate** [comment]
Unless you're relying on state in the server for subsequent tests (which seems fragile to me), I've always just booted up and shut down a server instance for each individual test case, by wrapping the test function in a `setup()` function of some kind.

**Comment by nkzawa** [comment]
I agree usually for http servers, but I'm talking about the case when it's heavy. For example, in my real issue, `puppeteer` is very slow to start and it's pain to start and stop for each test case. And the process never stop unless explicitly call `browser.close()`.
Another option is to add the `--forceExit` option which calls `process.exit()` when all tests finish but I think this is also not ideal.

**Comment by Qix-** [comment]
I'm confused; is the use-case a single server globally? Or is it a single server per test?

**Comment by TooTallNate** [comment]
Ya I see the use-case now. For cases where the "setup" takes a long time, booting up and shutting down a new server for each test ends up taking a long time. `process.on('exit')` or `process.on('beforeExit')` does indeed seem like the appropriate hook to me. `--forceExit` seems ok to me as well since this seems like an edge case.

**Comment by Qix-** [comment]
I have a solution for this that allows us to make an ordering guarantee, give me a little bit to make a PR.

**Comment by Qix-** [comment]
@nkzawa With #15, you can guarantee the order of tests being run.

This means you can start your file with a test that starts up the server and ends your file with a test that shuts down the server, and you can guarantee that they will run in that order.

**Comment by nkzawa** [comment]
Another option I think is to add a flag like the following.

```js
exports.shutDown = async () => {
  ....
}
exports.shutDown.teardown = true;
```

This way can be extended for other cases like skipping testcases `exports.aTest.skip = true`

**Comment by Qix-** [comment]
The problem I have with that is that it's something that requires looking things up in order to get a piece of functionality to work. With `best`, I can create a file and export functions without ever having to look at the documentation. That's a really nice feature of this test runner.

I think having functions run in order is a good contract to make. It's a functional guarantee that requires no a-priori knowledge of the library.

**Comment by Qix-** [comment]
Sounds good, feel free to comment back after using it a bit if it ends up not suiting your needs. I'd be interested to see if it solves the use-case.

Thanks @nkzawa!! :)
